use_frameworks!

target 'JKRouter_Example' do
  pod 'JKRouter', :path => '../'
  pod 'JKDataHelper'
  pod 'Masonry'
  pod 'YYModel'

target 'JKRouter_Tests' do
    inherit! :search_paths
    pod 'Kiwi'
    
  end
end
